### PR TITLE
Add functionality to allow for uploading SSL certificates to Controller

### PR DESCRIPTION
**Pull request by jsestrich**
I was looking for a way to automate uploading new SSL certificates to my controller and found your API. I've been successfully using this code to update my SSL certificates on my controller, so I figured I'd contribute back what I added.

### CODE REVIEW

**Comment by thannerfabian** [comment]
Looks like @ghaberek isn´t maintaining this repo anymore. Maybe you want to contribute to my fork.

**Comment by ghaberek** [comment]
> Looks like @ghaberek isn´t maintaining this repo anymore.

Please refrain from making assumptions about my involvement in my own project. I "maintain" this when I can, as best I can. I'll occasionally sweep through and merge some PRs and fix up some things but I've no specific intent or direction for anything. If anyone wants to provide more regular maintenance and improvement I'll gladly add them as a collaborator so they can push without waiting for me to approve a PR.

**Comment by ghaberek** [comment]
It looks like your "[tabify](https://github.com/jsestrich/omada-api/commit/602d883e5c9616c9d54e4c012f7759ea456eb59d)" commit also includes most of your code changes. I'm not sure how you would go about it, but I'd prefer to merge only the code changes and we can figure out "tabs vs spaces" changes later (FYI [PEP-8](https://peps.python.org/pep-0008/) says to prefer spaces).

**Comment by jsestrich** [comment]
phew. Took me a minute to get my git-fu back.

I realized I shouldn't commit all the individual parts here (it's just cluttering the log), and squashed it all into a single commit. I think this should be "just the code changes" now.

The tabify thing is a bit of a red-herring. If you look at the chain closely, I accidentally converted everything to spaces earlier in the chain and then later converted it back to leave things the way I found them.

I don't have a strong opinion on tabs vs. spaces (I'm happy to follow suit with whatever you'd like to do), but if you'd like I can also update everything to spaces in a separate pull request.

**Comment by jsestrich** [comment]
Just wanted to bump this thread. I think this code is ready for your review.

I have been using this successfully for a few months for auto-renewing my SSL certs.

**Pull request merged**
